-- Generated by scripts/make-testdata.py. Synthetic test data, do not edit by hand.

-- Local test DB only; on a real Supabase project, users come from Auth instead.



insert into auth.users (id, email) values
  ('aaaaaaaa-0000-4000-8000-000000000001', 'leon@example.com'),
  ('aaaaaaaa-0000-4000-8000-000000000002', 'member@example.com'),
  ('bbbbbbbb-0000-4000-8000-000000000003', 'outsider@example.com');

insert into public.profiles (id, name, website_url, social_links, created_at, backfill_status, last_web_search_at) values
  ('11111111-1111-4111-8111-111111111111', 'ReLU NTNU', 'https://www.relu-ntnu.no', array['https://www.instagram.com/relu_ntnu', 'https://www.linkedin.com/company/relu-ntnu']::text[], '2026-09-20T09:00:00Z', 'done', '2026-09-23T04:00:00Z'),
  ('22222222-2222-4222-8222-222222222222', 'Other Org AS', 'https://other.example', '{}'::text[], '2026-09-13T09:00:00Z', 'done', null);

insert into public.profile_members (profile_id, user_id, role, joined_at) values
  ('11111111-1111-4111-8111-111111111111', 'aaaaaaaa-0000-4000-8000-000000000001', 'owner', '2026-09-20T09:00:00Z'),
  ('11111111-1111-4111-8111-111111111111', 'aaaaaaaa-0000-4000-8000-000000000002', 'member', '2026-09-21T09:00:00Z'),
  ('22222222-2222-4222-8222-222222222222', 'bbbbbbbb-0000-4000-8000-000000000003', 'owner', '2026-09-13T09:00:00Z');

insert into public.keyword_rules (id, profile_id, term, context_terms, is_exclusion, created_at) values
  ('33333333-0000-4000-8000-000000000001', '11111111-1111-4111-8111-111111111111', 'ReLU NTNU', '{}'::text[], false, '2026-09-20T09:00:00Z'),
  ('33333333-0000-4000-8000-000000000002', '11111111-1111-4111-8111-111111111111', 'ReLU', array['NTNU', 'Trondheim', 'studentorganisasjon', 'student organization', 'linjeforening']::text[], false, '2026-09-20T09:00:00Z'),
  ('33333333-0000-4000-8000-000000000003', '11111111-1111-4111-8111-111111111111', 'activation function', '{}'::text[], true, '2026-09-20T09:00:00Z'),
  ('33333333-0000-4000-8000-000000000004', '11111111-1111-4111-8111-111111111111', 'aktiveringsfunksjon', '{}'::text[], true, '2026-09-20T09:00:00Z'),
  ('33333333-0000-4000-8000-000000000005', '11111111-1111-4111-8111-111111111111', 'leaky ReLU', '{}'::text[], true, '2026-09-20T09:00:00Z'),
  ('33333333-0000-4000-8000-000000000009', '22222222-2222-4222-8222-222222222222', 'Other Org', '{}'::text[], false, '2026-09-13T09:00:00Z');

insert into public.invites (id, profile_id, token, created_by, created_at, expires_at, used_at, used_by) values
  ('66666666-0000-4000-8000-000000000001', '11111111-1111-4111-8111-111111111111', 'testinvitetoken0000000000000000000000000000000001', 'aaaaaaaa-0000-4000-8000-000000000001', '2026-09-21T09:00:00Z', '2026-09-28T09:00:00Z', null, null);

insert into public.mentions (id, profile_id, url, title, snippet, source_type, source_name, published_at, fetched_at, reach_score, sentiment, sentiment_score, confidence, classifier_version, hidden) values
  ('44444444-0000-4000-8000-000000000001', '11111111-1111-4111-8111-111111111111', 'https://www.universitetsavisa.no/relu-hackathon', 'ReLU NTNU arrangerer AI-hackathon i Trondheim', 'Over 150 studenter deltok da ReLU NTNU arrangerte sitt første hackathon.', 'google_news', 'universitetsavisa.no', '2026-09-21T20:00:00Z', '2026-09-21T21:00:00Z', 0.41, null, null, null, null, false),
  ('44444444-0000-4000-8000-000000000002', '11111111-1111-4111-8111-111111111111', 'https://www.universitetsavisa.no/relu-hackathon', 'ReLU NTNU arrangerer AI-hackathon i Trondheim', '', 'gdelt', 'universitetsavisa.no', '2026-09-22T08:00:00Z', '2026-09-22T09:00:00Z', 0.41, null, null, null, null, false),
  ('44444444-0000-4000-8000-000000000003', '11111111-1111-4111-8111-111111111111', 'https://www.adressa.no/nyheter/relu-kvinner-maskinlaering', 'Studentorganisasjonen ReLU vil ha flere kvinner inn i maskinlæring', 'Studentorganisasjonen ved NTNU lanserer mentorprogram.', 'google_news', 'adressa.no', '2026-09-21T09:00:00Z', '2026-09-21T10:00:00Z', 0.66, null, null, null, null, false),
  ('44444444-0000-4000-8000-000000000004', '11111111-1111-4111-8111-111111111111', 'https://www.nrk.no/trondelag/ntnu-studenter-vant-ai', 'NTNU-studenter vant nordisk AI-konkurranse med ReLU NTNU-lag', 'Laget slo 40 andre universiteter.', 'google_news', 'nrk.no', '2026-09-18T07:00:00Z', '2026-09-18T08:00:00Z', 0.78, null, null, null, null, false),
  ('44444444-0000-4000-8000-000000000005', '11111111-1111-4111-8111-111111111111', 'https://www.itavisen.no/2026/09/19/relu-ntnu-nordic-student-ai-conference', 'ReLU NTNU hosts Nordic student AI conference', '', 'gdelt', 'itavisen.no', '2026-09-19T03:00:00Z', '2026-09-19T04:00:00Z', 0.49, null, null, null, null, false),
  ('44444444-0000-4000-8000-000000000006', '11111111-1111-4111-8111-111111111111', 'https://www.adressa.no/nyheter/trondheim/relu-apen-kildekode-modell', 'Trondheim-studenter i ReLU lanserer åpen kildekode-modell', '', 'gdelt', 'adressa.no', '2026-09-10T02:00:00Z', '2026-09-10T03:00:00Z', 0.66, null, null, null, null, false),
  ('44444444-0000-4000-8000-000000000007', '11111111-1111-4111-8111-111111111111', 'https://www.reddit.com/r/ntnu/comments/1abc01/anyone_joining_relu_ntnus_workshop_on_thursday/', 'Anyone joining ReLU NTNU''s workshop on Thursday?', 'Heard they are doing an intro to LLM fine-tuning. Is it beginner friendly?', 'reddit', 'r/ntnu', '2026-09-21T17:00:00Z', '2026-09-21T18:00:00Z', 0.35, null, null, null, null, false),
  ('44444444-0000-4000-8000-000000000008', '11111111-1111-4111-8111-111111111111', 'https://www.reddit.com/r/norge/comments/1abc03/studentforeningen_relu_pa_ntnu_holder_gratis/', 'Studentforeningen ReLU på NTNU holder gratis AI-kurs for alle', 'Åpent for alle i Trondheim, ikke bare studenter.', 'reddit', 'r/norge', '2026-09-19T14:00:00Z', '2026-09-19T15:00:00Z', 0.58, null, null, null, null, false),
  ('44444444-0000-4000-8000-000000000009', '11111111-1111-4111-8111-111111111111', 'https://www.reddit.com/r/trondheim/comments/1abc04/gratis_aikurs_for_studenter_denne_helgen/', 'Gratis AI-kurs for studenter denne helgen', 'Påmelding her: https://www.relu-ntnu.no/events/ai-kurs-host-2026', 'reddit', 'r/trondheim', '2026-09-19T09:00:00Z', '2026-09-19T10:00:00Z', 0.22, null, null, null, null, false),
  ('44444444-0000-4000-8000-000000000010', '11111111-1111-4111-8111-111111111111', 'https://www.relu-ntnu.no/about', 'ReLU NTNU – Student organization for AI at NTNU', 'ReLU NTNU is a student organization in Trondheim that makes applied AI accessible to all students.', 'web_search', 'relu-ntnu.no', '2026-09-20T16:00:00Z', '2026-09-20T17:00:00Z', 0.05, null, null, null, null, false),
  ('44444444-0000-4000-8000-000000000011', '11111111-1111-4111-8111-111111111111', 'https://www.nidaros.no/studentfrivillige-trondheim', 'Ti studentfrivillige som løfter Trondheim', 'Blant dem finner vi AI-miljøet bak @relu_ntnu på Instagram.', 'web_search', 'nidaros.no', '2026-09-17T03:00:00Z', '2026-09-17T04:00:00Z', 0.12, null, null, null, null, false),
  ('44444444-0000-4000-8000-000000000012', '11111111-1111-4111-8111-111111111111', 'https://www.digi.no/artikler/studentene-som-bygger-norsk-ai/560123', 'Studentene som bygger norsk AI', 'Linjeforeningen ReLU ved NTNU har vokst til over 400 medlemmer.', 'web_search', 'digi.no', '2026-09-11T13:00:00Z', '2026-09-11T14:00:00Z', 0.52, null, null, null, null, false),
  ('44444444-0000-4000-8000-000000000013', '11111111-1111-4111-8111-111111111111', 'https://www.universitetsavisa.no/relu-ntnu-starter-opp', 'ReLU NTNU starter opp: ny studentorganisasjon for kunstig intelligens', 'En ny studentorganisasjon ved NTNU vil gjøre anvendt AI tilgjengelig for alle studenter.', 'web_search', 'universitetsavisa.no', '2025-02-02T16:00:00Z', '2025-02-02T17:00:00Z', 0.41, null, null, null, null, false),
  ('44444444-0000-4000-8000-000000000014', '11111111-1111-4111-8111-111111111111', 'https://universitetsavisa.no/sak-0', 'ReLU NTNU på stand under Teknologiporten', '', 'google_news', 'universitetsavisa.no', '2026-09-07T20:00:00Z', '2026-09-07T21:00:00Z', 0.44, null, null, null, null, false),
  ('44444444-0000-4000-8000-000000000015', '11111111-1111-4111-8111-111111111111', 'https://adressa.no/sak-1', 'Studentorganisasjonen ReLU inviterer til bedriftspresentasjon', '', 'gdelt', 'adressa.no', '2026-08-30T02:00:00Z', '2026-08-30T03:00:00Z', 0.57, null, null, null, null, false),
  ('44444444-0000-4000-8000-000000000016', '11111111-1111-4111-8111-111111111111', 'https://www.reddit.com/r/ntnu/sak-2', 'ReLU NTNU samarbeider med SINTEF om sommerjobber', '', 'reddit', 'r/ntnu', '2026-08-20T19:00:00Z', '2026-08-20T20:00:00Z', 0.16, null, null, null, null, false),
  ('44444444-0000-4000-8000-000000000017', '11111111-1111-4111-8111-111111111111', 'https://digi.no/sak-3', 'Hva gjør egentlig ReLU på NTNU?', '', 'web_search', 'digi.no', '2026-08-11T15:00:00Z', '2026-08-11T16:00:00Z', 0.46, null, null, null, null, false),
  ('44444444-0000-4000-8000-000000000018', '11111111-1111-4111-8111-111111111111', 'https://nrk.no/sak-4', 'ReLU NTNU holds workshop on responsible AI', '', 'google_news', 'nrk.no', '2026-08-03T01:00:00Z', '2026-08-03T02:00:00Z', 0.83, null, null, null, null, false),
  ('44444444-0000-4000-8000-000000000019', '11111111-1111-4111-8111-111111111111', 'https://universitetsavisa.no/sak-5', 'ReLU-studenter i Trondheim bygger chatbot for Studentsamfundet', '', 'google_news', 'universitetsavisa.no', '2026-07-25T09:00:00Z', '2026-07-25T10:00:00Z', 0.45, null, null, null, null, false),
  ('44444444-0000-4000-8000-000000000020', '11111111-1111-4111-8111-111111111111', 'https://adressa.no/sak-6', 'ReLU NTNU søker nye styremedlemmer', '', 'gdelt', 'adressa.no', '2026-07-16T04:00:00Z', '2026-07-16T05:00:00Z', 0.74, null, null, null, null, false),
  ('44444444-0000-4000-8000-000000000021', '11111111-1111-4111-8111-111111111111', 'https://www.reddit.com/r/ntnu/sak-7', 'Nytt rekordopptak i ReLU NTNU', '', 'reddit', 'r/ntnu', '2026-07-06T20:00:00Z', '2026-07-06T21:00:00Z', 0.12, null, null, null, null, false),
  ('44444444-0000-4000-8000-000000000900', '11111111-1111-4111-8111-111111111111', 'https://www.reddit.com/r/MachineLearning/comments/1abc09/relu_ntnu_course_notes/', 'ReLU notes from NTNU TDT4265 lecture', 'Lecture notes about ReLU and its variants.', 'reddit', 'r/MachineLearning', '2026-09-16T09:00:00Z', '2026-09-16T09:00:00Z', 0.71, null, null, null, null, true),
  ('44444444-0000-4000-8000-000000000999', '22222222-2222-4222-8222-222222222222', 'https://news.example/other-org', 'Other Org AS opens new office', 'Private to Other Org''s members.', 'google_news', 'news.example', '2026-09-22T09:00:00Z', '2026-09-22T09:00:00Z', 0.3, null, null, null, null, false);

insert into public.runs (id, kind, profile_id, started_at, finished_at, status, stats, error) values
  ('55555555-0000-4000-8000-000000000001', 'hourly', null, '2026-09-23T08:05:00Z', '2026-09-23T08:07:00Z', 'success', '{"fetched": 84, "matched": 6, "inserted": 3, "per_source": {"google_news": 1, "gdelt": 1, "reddit": 1, "web_search": "skipped: not due"}}'::jsonb, null),
  ('55555555-0000-4000-8000-000000000002', 'hourly', null, '2026-09-23T07:05:00Z', '2026-09-23T07:06:00Z', 'failed', '{"fetched": 12, "matched": 0, "inserted": 0}'::jsonb, 'gdelt: HTTP 503 Service Unavailable'),
  ('55555555-0000-4000-8000-000000000003', 'backfill', '11111111-1111-4111-8111-111111111111', '2026-09-20T09:00:00Z', '2026-09-20T09:02:00Z', 'success', '{"fetched": 310, "matched": 19, "inserted": 19}'::jsonb, null),
  ('55555555-0000-4000-8000-000000000004', 'backfill', '22222222-2222-4222-8222-222222222222', '2026-09-13T09:00:00Z', '2026-09-13T09:01:00Z', 'success', '{"fetched": 20, "matched": 1, "inserted": 1}'::jsonb, null);

insert into public.quota_usage (provider, month, credits_used) values
  ('tavily', '2026-09-01', 412),
  ('exa', '2026-09-01', 0.0),
  ('serper', '2026-09-01', 38);
