/**
 * Synthetic test data (ReLU NTNU + one unrelated profile). Generated by
 * scripts/make-testdata.py together with supabase/seed.sql, so tests and the
 * seeded local database see the same rows. Use only in tests.
 */
import type { Invite, KeywordRule, Mention, Profile, ProfileMember, QuotaUsage, Run } from "@/lib/types";
import data from "./testdata.json";

export const FIXTURE_NOW: string = data.now;
export const fixtureUsers: { id: string; email: string }[] = data.users;
export const fixtureProfiles = data.profiles as Profile[];
export const fixtureMembers = data.profile_members as ProfileMember[];
export const fixtureKeywordRules = data.keyword_rules as KeywordRule[];
export const fixtureInvites = data.invites as Invite[];
export const fixtureMentions = data.mentions as Mention[];
export const fixtureRuns = data.runs as Run[];
export const fixtureQuotaUsage = data.quota_usage as QuotaUsage[];

export const RELU_PROFILE_ID = "11111111-1111-4111-8111-111111111111";
export const OTHER_PROFILE_ID = "22222222-2222-4222-8222-222222222222";

/** ReLU NTNU's own mentions (what a ReLU member may see). */
export const reluMentions = fixtureMentions.filter((m) => m.profile_id === RELU_PROFILE_ID);
